name: Update Apps Metadata
on:
  push:
    paths:
      - 'apps/**'
  pull_request:
    paths:
      - 'apps/**'
  workflow_dispatch:
jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          pip install pathlib
      - name: Update apps.json
        run: python .github/scripts/update_metadata.py
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Create logos archive
        run: |
          mkdir -p logo
          for app_dir in apps/*; do
            if [ -d "$app_dir" ]; then
              app_name=$(basename "$app_dir")
              # Create app-specific folder and copy logo as logo.png
              if [ -f "$app_dir/logo.png" ]; then
                mkdir -p "logo/${app_name}"
                cp "$app_dir/logo.png" "logo/${app_name}/logo.png"
              elif [ -f "$app_dir/icon"*.png ]; then
                mkdir -p "logo/${app_name}"
                cp "$app_dir/icon"*.png "logo/${app_name}/logo.png"
              fi
            fi
          done
          cd logo && zip -r ../logos.zip * && cd ..
      - name: Create Logos Release
        uses: softprops/action-gh-release@v1
        with:
          files: logos.zip
          tag_name: logos
          name: App Logos
          body: Archive of all app logos
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Apps Data Release
        uses: softprops/action-gh-release@v1
        with:
          files: data/apps.json
          tag_name: apps_data
          name: Apps Data
          body: Apps metadata JSON file
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push if changed
        if: steps.check_changes.outputs.changes == 'true'
        run: |-
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git add data/apps.json
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update apps metadata"
            git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:$BRANCH_NAME
          )

